metadata:
  pipeline_interfaces: pipeline_interface.yaml
  output_dir: ${HOME}/datadir
  sample_annotation: anno.tsv

attributes:
  provider: UCSC
  organism: Homo sapiens
  taxonomy_id: 9606
  
derived_columns: remote_url

data_sources:
  ucsc: hgdownload.cse.ucsc.edu/goldenpath/hg19/database/{sample_name}

implied_columns:
  organism:
    human:
      genome: hg19

bioconductor:
  rparse_code: parseEncodeRegions
